import type { HospitalDetails } from '../types/ae'

const defaultDetails = (cluster: string, district: string, hospitalName: string): HospitalDetails => ({
  cluster,
  district,
  address: `${district}, Hong Kong`,
  phone: {
    display: 'Contact HA for phone number',
    dialHref: null,
  },
  mapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${hospitalName}, Hong Kong`)}`,
})

const buildPhone = (display: string): HospitalDetails['phone'] => ({
  display,
  dialHref: `tel:+852${display.replace(/\s+/g, '')}`,
})

const withHAData = (
  cluster: string,
  district: string,
  hospitalName: string,
  enAddress: string,
  zhHospitalName: string,
  zhDistrict: string,
  zhAddress: string,
  phoneDisplay: string,
  lat: number,
  lng: number,
): HospitalDetails => ({
  cluster,
  district,
  address: enAddress,
  location: { lat, lng },
  localized: {
    'zh-HK': {
      hospitalName: zhHospitalName,
      district: zhDistrict,
      address: zhAddress,
    },
  },
  phone: buildPhone(phoneDisplay),
  mapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${zhHospitalName} ${hospitalName}, Hong Kong`)}`,
})

export const CLUSTER_ORDER = [
  'Hong Kong East',
  'Hong Kong West',
  'Kowloon Central',
  'Kowloon East',
  'Kowloon West',
  'New Territories East',
  'New Territories West',
] as const

export const TRIAGE_CATEGORY_LABELS = {
  I: 'Triage Category I',
  II: 'Triage Category II',
  III: 'Triage Category III',
  IV_V: 'Triage Category IV & V',
} as const

export const HOSPITAL_META: Record<string, HospitalDetails> = {
  'Pamela Youde Nethersole Eastern Hospital': withHAData(
    'Hong Kong East',
    'Chai Wan',
    'Pamela Youde Nethersole Eastern Hospital',
    '3 Lok Man Road, Chai Wan, HK',
    '東區尤德夫人那打素醫院',
    '柴灣',
    '香港柴灣樂民道 3 號',
    '2595 6111',
    22.2696,
    114.2369,
  ),
  'Queen Mary Hospital': withHAData(
    'Hong Kong West',
    'Pok Fu Lam',
    'Queen Mary Hospital',
    '102 Pokfulam Road, HK',
    '瑪麗醫院',
    '薄扶林',
    '香港薄扶林道 102 號',
    '2255 3838',
    22.2702,
    114.1316,
  ),
  'Ruttonjee Hospital': withHAData(
    'Hong Kong East',
    'Wan Chai',
    'Ruttonjee Hospital',
    "266 Queen's Road East, Wan Chai, HK",
    '律敦治醫院',
    '灣仔',
    '香港灣仔皇后大道東 266 號',
    '2291 2000',
    22.2747,
    114.1794,
  ),
  'St John Hospital': withHAData(
    'Hong Kong East',
    'Cheung Chau',
    'St John Hospital',
    'Cheung Chau Hospital Road, Tung Wan, Cheung Chau',
    '長洲醫院',
    '長洲',
    '長洲東灣長洲醫院路',
    '2986 2100',
    22.2086,
    114.0287,
  ),
  'Queen Elizabeth Hospital': withHAData(
    'Kowloon Central',
    'Yau Ma Tei',
    'Queen Elizabeth Hospital',
    '30 Gascoigne Road, KLN',
    '伊利沙伯醫院',
    '油麻地',
    '九龍加士居道 30 號',
    '3506 8888',
    22.3121,
    114.1748,
  ),
  'Kwong Wah Hospital': withHAData(
    'Kowloon Central',
    'Yau Ma Tei',
    'Kwong Wah Hospital',
    '25 Waterloo Road, KLN',
    '廣華醫院',
    '油麻地',
    '九龍窩打老道 25 號',
    '2332 2311',
    22.3126,
    114.1707,
  ),
  'United Christian Hospital': withHAData(
    'Kowloon East',
    'Kwun Tong',
    'United Christian Hospital',
    '130 Hip Wo Street, Kwun Tong, KLN',
    '基督教聯合醫院',
    '觀塘',
    '九龍觀塘協和街 130 號',
    '3949 4000',
    22.316,
    114.227,
  ),
  'Tseung Kwan O Hospital': withHAData(
    'Kowloon East',
    'Tseung Kwan O',
    'Tseung Kwan O Hospital',
    'No. 2 Po Ning Lane, Hang Hau, Tseung Kwan O',
    '將軍澳醫院',
    '將軍澳',
    '將軍澳坑口寶寧里 2 號',
    '2208 0111',
    22.3158,
    114.2717,
  ),
  'Caritas Medical Centre': withHAData(
    'Kowloon West',
    'Sham Shui Po',
    'Caritas Medical Centre',
    '111 Wing Hong Street, Sham Shui Po, KLN',
    '明愛醫院',
    '深水埗',
    '九龍深水埗永康街 111 號',
    '3408 7911',
    22.3405,
    114.1515,
  ),
  'Princess Margaret Hospital': withHAData(
    'Kowloon West',
    'Lai Chi Kok',
    'Princess Margaret Hospital',
    '2-10 Princess Margaret Hospital Road, Kwai Chung, New Territories',
    '瑪嘉烈醫院',
    '葵涌',
    '新界葵涌瑪嘉烈醫院路 2-10 號',
    '2990 1111',
    22.3404,
    114.1376,
  ),
  'Yan Chai Hospital': withHAData(
    'Kowloon West',
    'Tsuen Wan',
    'Yan Chai Hospital',
    '7-11 Yan Chai Street, Tsuen Wan, NT',
    '仁濟醫院',
    '荃灣',
    '新界荃灣仁濟街 7-11 號',
    '2417 8383',
    22.3705,
    114.1187,
  ),
  'Alice Ho Miu Ling Nethersole Hospital': withHAData(
    'New Territories East',
    'Tai Po',
    'Alice Ho Miu Ling Nethersole Hospital',
    '11 Chuen On Road, Tai Po, NT',
    '雅麗氏何妙齡那打素醫院',
    '大埔',
    '新界大埔全安路 11 號',
    '2689 2000',
    22.4501,
    114.1694,
  ),
  'North District Hospital': withHAData(
    'New Territories East',
    'Sheung Shui',
    'North District Hospital',
    '9 Po Kin Road, Sheung Shui, New Territories',
    '北區醫院',
    '上水',
    '新界上水保健路 9 號',
    '2683 8888',
    22.5017,
    114.1277,
  ),
  'Prince of Wales Hospital': withHAData(
    'New Territories East',
    'Sha Tin',
    'Prince of Wales Hospital',
    '30-32 Ngan Shing Street, Shatin, NT',
    '威爾斯親王醫院',
    '沙田',
    '新界沙田銀城街 30-32 號',
    '3505 2211',
    22.4066,
    114.2105,
  ),
  'North Lantau Hospital': withHAData(
    'New Territories West',
    'Tung Chung',
    'North Lantau Hospital',
    '1/F, 8 Chung Yan Road, Tung Chung, Lantau, N.T.',
    '北大嶼山醫院',
    '東涌',
    '大嶼山東涌松仁路 8 號',
    '3467 7000',
    22.2866,
    113.9436,
  ),
  'Pok Oi Hospital': withHAData(
    'New Territories West',
    'Yuen Long',
    'Pok Oi Hospital',
    'Au Tau, Yuen Long, NT',
    '博愛醫院',
    '元朗',
    '新界元朗坳頭',
    '2486 8000',
    22.4451,
    114.0347,
  ),
  'Tin Shui Wai Hospital': withHAData(
    'New Territories West',
    'Tin Shui Wai',
    'Tin Shui Wai Hospital',
    '11 Tin Tan Street, Tin Shui Wai, New Territories',
    '天水圍醫院',
    '天水圍',
    '新界天水圍天壇街 11 號',
    '3513 5000',
    22.4606,
    114.0027,
  ),
  'Tuen Mun Hospital': withHAData(
    'New Territories West',
    'Tuen Mun',
    'Tuen Mun Hospital',
    '23 Tsing Chung Koon Road, Tuen Mun, NT',
    '屯門醫院',
    '屯門',
    '新界屯門青松觀路 23 號',
    '2468 5111',
    22.4073,
    113.9769,
  ),
}

export function getHospitalDetails(hospitalName: string): HospitalDetails {
  const known = HOSPITAL_META[hospitalName]
  if (known) {
    return known
  }

  return defaultDetails('Other', 'Unknown', hospitalName)
}
